#!/usr/bin/env node
/**
 * seal-env.mjs — 把 .env 封印为运行时只读配置（模拟「打包后不可编辑」）。
 *
 * .env 的唯一消费者就是本脚本。封印后生成 sealed-config.gen.mjs：
 *   - 运行时（snapshot-uploader.mjs）只加载该模块，永不读 .env；
 *   - 模块内含 SHA-256 封印摘要，手工改动值会导致 verify() 失败、进程拒绝启动；
 *   - 想改配置 = 改 .env 后重跑本脚本（等同重新打包）。
 *
 * 用法：node seal-env.mjs
 */
import { createHash, randomBytes } from "node:crypto";
import { readFile, writeFile, access } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const envPath = path.join(here, ".env");
const outPath = path.join(here, "sealed-config.gen.mjs");

const REQUIRED_KEYS = [
  "ZCODE_ENDPOINT_ORIGIN",
  "ZCODE_SNAPSHOT_CREDENTIAL_PATH",
  "OSS_POST_ENDPOINT",
  "ZCODE_SNAPSHOT_AUTH_TOKEN",
];

async function exists(p) {
  try { await access(p); return true; } catch { return false; }
}

function parseEnv(text) {
  const values = {};
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq <= 0) throw new Error(`.env 行格式非法: ${rawLine}`);
    values[line.slice(0, eq).trim()] = line.slice(eq + 1).trim();
  }
  return values;
}

if (!(await exists(envPath))) {
  console.error("[seal] 未找到 .env，请先按 .env.example 配置端点。");
  process.exit(2);
}

const values = parseEnv(await readFile(envPath, "utf8"));
const missing = REQUIRED_KEYS.filter((k) => !values[k]);
if (missing.length) {
  console.error(`[seal] .env 缺少必需键: ${missing.join(", ")}`);
  process.exit(2);
}

// 只封印已知键，防止通过 .env 塞入额外运行时行为。
const sealedValues = {};
for (const k of REQUIRED_KEYS) sealedValues[k] = values[k];

const salt = randomBytes(16).toString("hex");
const canonical = Object.keys(sealedValues).sort()
  .map((k) => `${k}=${sealedValues[k]}`).join("\n");
const digest = createHash("sha256")
  .update(`sealed:${salt}:${canonical}`).digest("hex");

const banner = "// AUTO-GENERATED by seal-env.mjs — 手工编辑会被封印校验拒绝。\n";
const code = `${banner}import { createHash } from "node:crypto";

export const VALUES = Object.freeze(${JSON.stringify(sealedValues, null, 2)});

export const SEAL = Object.freeze({
  algorithm: "sha256",
  salt: ${JSON.stringify(salt)},
  digest: ${JSON.stringify(digest)},
  sealedAt: ${JSON.stringify(new Date().toISOString())},
  source: ".env",
});

function canonical(v) {
  return Object.keys(v).sort().map((k) => \`\${k}=\${v[k]}\`).join("\\n");
}

export function verify() {
  const actual = createHash("sha256")
    .update(\`sealed:\${SEAL.salt}:\${canonical(VALUES)}\`)
    .digest("hex");
  return actual === SEAL.digest;
}
`;

await writeFile(outPath, code, "utf8");
console.log(`[seal] 已封印 ${REQUIRED_KEYS.length} 个配置项 -> ${path.basename(outPath)}`);
console.log(`[seal] 摘要: ${digest.slice(0, 16)}…（sealedAt 已写入模块）`);
